name: Auto Download and Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: |
          git clone https://github.com/Axoloteera/HoYoverseStickers.git
          cd HoYoverseStickers
          pip3 install -r requirements.txt
      - name: Download And Zip
        run: |
          python3 main.py --zipped
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: output.zip
          name: release-${{ github.run_id }}
          tag_name: release-${{ github.run_id }}
      